### ISSUE TITLE
Enabling JS errors interferes with frontend JS

### ISSUE THREAD

**Issue by russback** [born05/craft-sentry#16]
Bit of a strange one this.

There are no errors reported in the console, just notifications as Sentry does its thing. However on a page where there is a Craft Commerce Stripe payment intent form, the JavaScript SDK that loads from Stripe doesn't initiate so the payment form doesn't work.

Changing `reportJsErrors` to `false` resolves the issue, so appears to be down to Sentry's JS tracking.

**Comment by roelvanhintum** [comment]
@russback can you provide some additional info? Error messages or something? I've just setup a basic commerce environment using the example templates with the stripe gateway and sentry js reporting, but everything seems to work fine.

**Comment by russback** [comment]
Sorry @roelvanhintum this one was put on hold, and is no longer showing this behaviour.
