### ISSUE TITLE
Craft SystemReport shows OutOfBoundsException error when craft-sentry is enabled

### ISSUE THREAD

**Issue by russback** [born05/craft-sentry#17]
The System Report at `/admin/utilities/system-report` throws an error:

```
OutOfBoundsException
Package "yiisoft/yii2" is not installed
```

With craft-sentry disabled, this page displays fine.

Craft Pro 3.6.2
PHP 7.4.14

**Comment by russback** [comment]
Craft support are looking into this, as [it's been raised by somebody else](https://github.com/craftcms/cms/issues/7493). I also get the same issue when using [an alternative plugin](https://github.com/diginov/craft-sentry-logger/).

**Comment by roelvanhintum** [comment]
Thanks @russback i did not know this.

**Comment by russback** [comment]
Resolved in https://github.com/craftcms/cms/commit/cbdd57c66e3cd62f0768630b6e79f0f4489663a0
