### ISSUE TITLE
Include autoSessionTracking setting in JS integration

### ISSUE THREAD

**Issue by rocknrolaf** [born05/craft-sentry#19]
Would it be possible to include another setting into the JS integration?

It could be nice to disable this due to privacy issues and also some CORS issues (see e.g. https://github.com/getsentry/sentry-javascript/issues/2859#issuecomment-828312873)

Thanks!

**Comment by roelvanhintum** [comment]
@rocknrolaf released in 1.1.1

Does this work for you?

**Comment by rocknrolaf** [comment]
@roelvanhintum thanks for the quick response!

Unfortunatly the integration for Browsertracing "integrations: [new Sentry.Integrations.BrowserTracing()]," also seems to trigger an envelope call to sentry.
Without the "integrations" part the autoSessionTracking setting works and i could disable these requests.
Would it be possible to also deactivate this integration by a setting? If i get it right this integration is for performance monitoring? (https://docs.sentry.io/platforms/javascript/performance/)
Sorry for not testing this earlier...

**Comment by roelvanhintum** [comment]
@rocknrolaf, in release 1.1.2 you can disable `performanceMonitoring` to remove the integrations part. Does that fix it?

**Comment by rocknrolaf** [comment]
@roelvanhintum yes it works! thank you!
