### ISSUE TITLE
NotFoundHttpException from templates

### ISSUE THREAD

**Issue by kringkaste** [born05/craft-sentry#24]
If you use the exit function within Twig like

```twig
{% exit 404 %}
```

the exception is captured and transmitted to Sentry even if you excluded the code (404) in the plugins config. The `NotFoundHttpException` exception is catched by `Twig\Error\RuntimeError`. This is new since Craft 4. We are running Craft 4.2.2 having this issue. I'm not sure, if this can be fixed by your plugin.

**Comment by kringkaste** [comment]
Please see #26

**Comment by roelvanhintum** [comment]
Thanks! Released in 2.0.1
