### ISSUE TITLE
excludedCodes is not used anymore

### ISSUE THREAD

**Issue by boboldehampsink** [born05/craft-sentry#4]
Since latest update

**Comment by roelvanhintum** [comment]
You are right. That should be fixed. Sentry captures the errors without the plugin's event handler. I should change this back.

**Comment by boboldehampsink** [comment]
Any ETA? Getting spammed by Sentry right now

**Comment by roelvanhintum** [comment]
@boboldehampsink sorry about that. You can use 1.0.0 which still has the excludedCodes. I've just committed a change that should fix this, but it needs testing. Our own sentry is out because of a use peak in users...

**Comment by roelvanhintum** [comment]
@boboldehampsink fixed in 1.0.3
