### ISSUE TITLE
Not logging in devMode

### ISSUE THREAD

**Issue by jerome2710** [born05/craft-sentry#6]
According to the README.md and the if-statement in the init-function, the plugin will not log exceptions in `devMode`. May I ask why you made this choice?

I always would like to test things before updating the live website. Disabling `devMode` could be an option, but as there already is an config option `enabled`, why not configure this option from environment variables?

Eg.:

`SENTRY_ENABLED=true`

and

`'enabled' => getenv('SENTRY_ENABLED')`

The development `.env`-file would then disable Sentry, while the `.env.production` enable it when replacing `.env` during deployment. It feels strange checking both `enabled` and `devMode`.

**Comment by roelvanhintum** [comment]
@jerome2710 you are right. Fixed in 1.0.3
