### ISSUE TITLE
Error when used in conjunction with Link field plugin

### ISSUE THREAD

**Issue by dustinwalker** [born05/craft-sentry#8]
When Sentry is enabled, I'm running across this issue: https://github.com/sebastian-lenz/craft-linkfield/issues/79

It seems to stem from a change in Craft 3.3+ but I'm linking references that seem to better understand the core issue:

- https://github.com/verbb/knock-knock/issues/12
- https://github.com/mmikkel/CpFieldInspect-Craft/issues/14#issuecomment-544685026
- https://github.com/sebastian-lenz/craft-linkfield/issues/79#issuecomment-561860449

I'm running:
- Craft 3.5.12.1
- Linkfield 2.0.0-beta.10 (sebastianlenz/linkfield)
- Craft Sentry 1.0.6

Let me know if you need any more info.
Thanks!
Dustin

**Comment by roelvanhintum** [comment]
@dustinwalker, thanks for the issue! To be clear are you seeing a similar error caused by the sentry plugin, or are you seeing the error caused by the link field plugin? If you could provide a stacktrace it would help a lot.

**Comment by dustinwalker** [comment]
Attached is the stacktrace. The error is thrown with the Link field plugin but my understanding is that it is caused because this plugin assumes the app is fully bootstrapped and should instead fire on the EVENT_AFTER_LOAD_PLUGINS : https://github.com/craftcms/cms/issues/4944#issuecomment-532258934

You should be able to replicate it locally by having the sentry plugin installed then installing:
 "sebastianlenz/linkfield": "^2.0.0-beta.10",

As soon as I'm in an environment that sentry is reporting, the admin throws the error below.

Hope that helps.

Stack trace:
#0 /Users/dustinwalker/projects/plugins/toolkit/vendor/yiisoft/yii2/i18n/I18N.php(89): yii\i18n\I18N->getMessageSource('typedlinkfield')
#1 /Users/dustinwalker/projects/plugins/toolkit/vendor/craftcms/cms/src/i18n/I18N.php(321): yii\i18n\I18N->translate('typedlinkfield', 'Input fields', Array, 'en-US')
#2 /Users/dustinwalker/projects/plugins/toolkit/vendor/yiisoft/yii2/BaseYii.php(538): craft\i18n\I18N->translate('typedlinkfield', 'Input fields', Array, 'en-US')
#3 /Users/dustinwalker/projects/plugins/toolkit/vendor/sebastianlenz/linkfield/src/models/LinkType.php(104): yii\BaseYii::t('typedlinkfield', 'Input fields')
#4 /Users/dustinwalker/projects/plugins/toolkit/vendor/sebastianlenz/linkfield/src/fields/LinkField.php(97): lenz\linkfield\models\LinkType->getTranslatedDisplayGroup()
#5 [internal function]: lenz\linkfield\fields\LinkField->lenz\linkfield\fields\{closure}(Object(lenz\linkfield\models\input\InputLinkType), Object(lenz\linkfield\models\input\InputLinkType))
#6 /Users/dustinwalker/projects/plugins/toolkit/vendor/sebastianlenz/linkfield/src/fields/LinkField.php(100): uasort(Array, Object(Closure))
#7 /Users/dustinwalker/projects/plugins/toolkit/vendor/sebastianlenz/linkfield/src/fields/LinkField.php(248): lenz\linkfield\fields\LinkField->getAvailableLinkTypes()
#8 /Users/dustinwalker/projects/plugins/toolkit/vendor/yiisoft/yii2/base/Component.php(180): lenz\linkfield\fields\LinkField->setTypeSettings(Array)
#9 /Users/dustinwalker/projects/plugins/toolkit/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('typeSettings', Array)
#10 /Users/dustinwalker/projects/plugins/toolkit/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(lenz\linkfield\fields\LinkField), Array)
#11 [internal function]: yii\base\BaseObject->__construct(Array)
#12 /Users/dustinwalker/projects/plugins/toolkit/vendor/yiisoft/yii2/di/Container.php(406): ReflectionClass->newInstanceArgs(Array)
#13 /Users/dustinwalker/projects/plugins/toolkit/vendor/yiisoft/yii2/di/Container.php(165): yii\di\Container->build('lenz\\linkfield\\...', Array, Array)
#14 /Users/dustinwalker/projects/plugins/toolkit/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('lenz\\linkfield\\...', Array, Array)
#15 /Users/dustinwalker/projects/plugins/toolkit/vendor/craftcms/cms/src/helpers/Component.php(111): yii\BaseYii::createObject(Array)
#16 /Users/dustinwalker/projects/plugins/toolkit/vendor/craftcms/cms/src/services/Fields.php(561): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#17 /Users/dustinwalker/projects/plugins/toolkit/vendor/craftcms/cms/src/services/Fields.php(586): craft\services\Fields->createField(Array)
#18 /Users/dustinwalker/projects/plugins/toolkit/vendor/craftcms/cms/src/services/Fields.php(615): craft\services\Fields->_fields(NULL)
#19 /Users/dustinwalker/projects/plugins/toolkit/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1999): craft\services\Fields->getAllFields()
#20 /Users/dustinwalker/projects/plugins/toolkit/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1354): craft\elements\db\ElementQuery->customFields()
#21 /Users/dustinwalker/projects/plugins/toolkit/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#22 /Users/dustinwalker/projects/plugins/toolkit/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\EntryQuery))
#23 /Users/dustinwalker/projects/plugins/toolkit/vendor/yiisoft/yii2/db/Query.php(285): yii\db\Query->createCommand(Object(craft\db\Connection))
#24 /Users/dustinwalker/projects/plugins/toolkit/vendor/craftcms/cms/src/db/Query.php(168): yii\db\Query->one(NULL)
#25 /Users/dustinwalker/projects/plugins/toolkit/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1499): craft\db\Query->one(NULL)
#26 /Users/dustinwalker/projects/plugins/toolkit/vendor/craftcms/cms/src/services/Elements.php(511): craft\elements\db\ElementQuery->one()
#27 /Users/dustinwalker/projects/plugins/toolkit/vendor/craftcms/cms/src/services/Elements.php(579): craft\services\Elements->getElementById(2, 'craft\\elements\\...', 1)
#28 /Users/dustinwalker/projects/plugins/toolkit/vendor/craftcms/cms/src/web/UrlManager.php(383): craft\services\Elements->getElementByUri('__home__', 1, true)
#29 /Users/dustinwalker/projects/plugins/toolkit/vendor/craftcms/cms/src/web/UrlManager.php(225): craft\web\UrlManager->_getMatchedElementRoute(Object(craft\web\Request))
#30 /Users/dustinwalker/projects/plugins/toolkit/plugins/astuteo-toolkit/src/AstuteoToolkit.php(169): craft\web\UrlManager->getMatchedElement()
#31 [internal function]: astuteo\astuteotoolkit\AstuteoToolkit->astuteo\astuteotoolkit\{closure}(Object(yii\base\Event))
#32 /Users/dustinwalker/projects/plugins/toolkit/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(yii\base\Event))
#33 /Users/dustinwalker/projects/plugins/toolkit/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\web\\View', 'endBody', Object(yii\base\Event))
#34 /Users/dustinwalker/projects/plugins/toolkit/vendor/yiisoft/yii2/web/View.php(159): yii\base\Component->trigger('endBody')
#35 /Users/dustinwalker/projects/plugins/toolkit/vendor/craftcms/cms/src/web/View.php(1102): yii\web\View->endBody()
#36 /Users/dustinwalker/projects/plugins/toolkit/vendor/yiisoft/yii2/views/errorHandler/exception.php(538): craft\web\View->endBody()
#37 /Users/dustinwalker/projects/plugins/toolkit/vendor/yiisoft/yii2/base/View.php(348): require('/Users/dustinwa...')
#38 /Users/dustinwalker/projects/plugins/toolkit/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/Users/dustinwa...', Array)
#39 /Users/dustinwalker/projects/plugins/toolkit/vendor/yiisoft/yii2/web/ErrorHandler.php(270): yii\base\View->renderFile('/Users/dustinwa...', Array, Object(craft\web\ErrorHandler))
#40 /Users/dustinwalker/projects/plugins/toolkit/vendor/yiisoft/yii2/web/ErrorHandler.php(127): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#41 /Users/dustinwalker/projects/plugins/toolkit/vendor/craftcms/cms/src/web/ErrorHandler.php(139): yii\web\ErrorHandler->renderException(Object(yii\base\InvalidConfigException))
#42 /Users/dustinwalker/projects/plugins/toolkit/vendor/yiisoft/yii2/base/ErrorHandler.php(135): craft\web\ErrorHandler->renderException(Object(yii\base\InvalidConfigException))
#43 /Users/dustinwalker/projects/plugins/toolkit/vendor/craftcms/cms/src/web/ErrorHandler.php(63): yii\base\ErrorHandler->handleException(Object(yii\base\InvalidConfigException))
#44 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\base\InvalidConfigException))
#45 {main}

**Comment by jamesedmonston** [comment]
@roelvanhintum I had a similar problem with the 2-factor authentication plugin.

https://github.com/ethercreative/craft-twofactorauthentication/blob/master/src/Plugin.php#L51

Adding `Event::on(Plugins::class, Plugins::EVENT_AFTER_LOAD_PLUGINS, function () { ... }` around the plugin initialisation seems to fix the issue 👍🏻

I just tried it locally and it resolves the issue with this plugin, too.

**Comment by roelvanhintum** [comment]
Just pushed to master. @dustinwalker and @jamesedmonston does this work for you? I'll wait with the release because it's friday. ;)
@jamesedmonston same goes for the 2fa plugin.

Because sentry needs to load as soon as possible, i've only moved the part where data from the user identity is loaded.

**Comment by jamesedmonston** [comment]
@roelvanhintum Thanks for looking into this quickly. Makes sense about only moving the required bit into the event!

**Comment by dustinwalker** [comment]
@roelvanhintum Thanks for the update! I tested it quickly and got the following error. That may be something on my end. I can test more throughly, but thought I'd share now in case it's something that makes sense to you.


```
Undefined variable: app

$options['default_integrations'] = false;
        }
 
        Sentry\init($options);
 
        /**
         * Setup user
         */
        Event::on(Plugins::class, Plugins::EVENT_AFTER_LOAD_PLUGINS, function () {
            $user = $app->getUser()->getIdentity();
 
            Sentry\configureScope(function (Scope $scope) use ($settings, $user) {
                if ($user && !$settings->anonymous) {
                    $scope->setUser([
                        'ID'       => $user->id,
                        'Username' => $user->username,
                        'Email'    => $user->email,
                        'Admin'    => $user->admin ? 'Yes' : 'No',
                    ]); 
```
